### PR TITLE
Review

### PR DESCRIPTION
**Pull request by BrittanyBlake**
Mint Sign Up Form Project:

We created a clone of Mint's sign up page using HTML and CSS. 

Stickler is showing error with the indentation but it appears fine on our editor.

### CODE REVIEW

**Review by rOluochKe — COMMENTED** [review]
### Under review...

**Review by rOluochKe — CHANGES_REQUESTED** [review]
@BrittanyBlake and @davisdambis 
### Good job for the work done so far, this is impressive. However, there are a few changes you need to work on and make the project even better.
- Make the logos for mint, quickbooks and turbotax smaller like in the design
- Work on your margin between the input fields(email, phone, password and the button) smaller, rfer from design
- On your footer and end of page add a margin bottom
- Validate your index file with html5 online validator tool and fix the required changes [Refer this guide](https://validator.w3.org/#validate_by_upload)
- Fix the linting error on your files as well

**You can always reach out for help on slack, your team, mentor and any TSE**
### Once you have made all these changes, resubmit for another review. All the best in the next submission.

**Comment by BrittanyBlake** [comment]
Mint Sign Up Form Project:

-We made the logos for Mint, QuickBooks, and TurboTax smaller. 
-We fixed the margins between input fields. 
-We added a bottom margin on our footer and bottom of the page.
-We validated our index file and fixed the warnings. 
-We fixed the linter errors. 

Live Demo:
https://rawcdn.githack.com/BrittanyBlake/HTML-forms/aadf4cc8bee115909ef9144f83f4660e4c9c1d8c/index.html

**Review by fatymahmed — APPROVED** [review]
## Hi @BrittanyBlake @davisdambis,
Your project looks good.

[OPTIONAL]
- You could reduce the `margin-top` on 'Invisible reCAPTCHA by ...' part.
It's a 👍🏾 from me!
## ✔️ Approved!

Good luck with your next projects.
_Don't forget to submit your project completion form_

**Pull request merged**
